###
# ansible-playbook -i <inventory> playbook/disable_slurmd.yml
#
##
---
- name: Reboot baremetal hosts
  hosts: baremetal
  become: true  
  tasks:
    - name: Reboot hosts and wait for them to come back online
      ansible.builtin.reboot:
        msg: "Rebooting to prepare for cleanup tasks"
        pre_reboot_delay: 10
        post_reboot_delay: 30
        reboot_timeout: 600

- name: Post-cleanup - Remove Docker SDK and Docker engine from baremetal hosts
  hosts: baremetal
  become: true
  gather_facts: true
  tasks:
    - ansible.builtin.include_role:
        name: post-cleanup
        tasks_from: remove_docker_sdk
      tags: [remove_docker_sdk]

    - ansible.builtin.include_role:
        name: post-cleanup
        tasks_from: cleanup_docker
      tags: [cleanup_docker]

- name: Post-cleanup - Remove /etc/hosts generated block from all hosts
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - ansible.builtin.include_role:
        name: post-cleanup
        tasks_from: remove_etc_hosts_block
      tags: [remove_etc_hosts_block]

- name: Start and enable slurmd service
  hosts: all
  become: true
  tasks:
    - name: Start and enable slurmd
      ansible.builtin.systemd:
        name: slurmd
        state: started
        enabled: true

    - name: RESUME node in Slurm
    # 註解: 獲取具管理員權限的使用者，並在 Slurm 叢集中將 resume 該節點。
      ansible.builtin.shell: |
        THIS_NODE=$(hostname -s)
        SLURM_ADMIN=$(sacctmgr show user withassoc format=user,adminlevel -n -P | grep -i 'Administ' | cut -d'|' -f1 | head -n 1)
        
        if [ -z "$SLURM_ADMIN" ]; then
          echo "Error: Cannot find Slurm Administrator account."
          exit 1
        fi
        #echo "RUN: sudo su - \"$SLURM_ADMIN\" -c \"scontrol update NodeName=${THIS_NODE} State=RESUME \""
        sudo su - "$SLURM_ADMIN" -c "scontrol update NodeName=${THIS_NODE} State=RESUME"
      args:
        executable: /bin/bash

- name: Start NFS client related services
  hosts: all
  become: true

  tasks:
    - name: Start and enable NFS client related services
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: started
        enabled: true
      loop:
        - rpcbind.socket
        - rpcbind.service
        - nfs-client.target
        - nfs-common.service
        - nfs-utils.service
        - autofs.service
      ignore_errors: true
      when: false

    - name: Mount all NFS file systems
      ansible.builtin.shell: mount -a -t nfs,nfs4 || true
      args:
        executable: /bin/bash
      when: false
