#!/bin/bash
# Slurm Head Node installation (controller + NFS + DB + SlurmDBD + Slurmctld)
# Generated by Terraform — do not edit manually.
set -e

CONTROLLER_HOSTNAME="${controller_hostname}"
NFS_SHARE_DIR="${nfs_share_dir}"
DB_PASSWORD="${db_password}"
CLUSTER_NAME="${cluster_name}"
MUNGE_KEY_SYNC="$NFS_SHARE_DIR/munge.key.sync"
SLURM_CONF_SYNC="$NFS_SHARE_DIR/slurm.conf.sync"

echo "========== 開始安裝 Head Node ($CONTROLLER_HOSTNAME) =========="

# Set hostname
hostnamectl set-hostname "$CONTROLLER_HOSTNAME"

# Resolve own IP (first NIC = default network)
CONTROLLER_IP=$(hostname -I | awk '{print $1}')
echo "$CONTROLLER_IP $CONTROLLER_HOSTNAME" >> /etc/hosts

# ---------- packages ----------
echo "=> 安裝基礎套件"
dnf install -y epel-release
dnf config-manager --set-enabled crb
dnf install -y munge munge-libs munge-devel \
               slurm slurm-slurmd slurm-slurmctld slurm-slurmdbd \
               nfs-utils mariadb-server apptainer make tmux

# ---------- users ----------
echo "=> 確保 slurm / munge 使用者與群組存在"
getent group slurm  >/dev/null || groupadd -r slurm
getent passwd slurm >/dev/null || useradd -r -g slurm -s /bin/nologin -d /nonexistent slurm
getent group munge  >/dev/null || groupadd -r munge
getent passwd munge >/dev/null || useradd -r -g munge -s /bin/nologin -d /nonexistent munge

# ---------- MUNGE ----------
echo "=> 設定 MUNGE"
if [ ! -f /etc/munge/munge.key ]; then
    /usr/sbin/create-munge-key
fi
chown munge:munge /etc/munge/munge.key
chmod 400 /etc/munge/munge.key
systemctl enable --now munge

# Share MUNGE key via NFS for compute nodes
cp /etc/munge/munge.key "$MUNGE_KEY_SYNC"
chmod 644 "$MUNGE_KEY_SYNC"

# ---------- NFS Server ----------
echo "=> 設定 NFS Server"
if ! grep -q "$NFS_SHARE_DIR" /etc/exports; then
    echo "$NFS_SHARE_DIR ${nfs_network_cidr}(rw,sync,no_root_squash,no_subtree_check)" >> /etc/exports
    exportfs -arv
fi
systemctl enable --now nfs-server

# ---------- MariaDB ----------
echo "=> 設定 MariaDB"
systemctl enable --now mariadb
mysql -e "CREATE DATABASE IF NOT EXISTS slurm_acct_db;"
mysql -e "CREATE USER IF NOT EXISTS 'slurm'@'localhost' IDENTIFIED BY '$DB_PASSWORD';"
mysql -e "GRANT ALL PRIVILEGES ON slurm_acct_db.* TO 'slurm'@'localhost';"
mysql -e "FLUSH PRIVILEGES;"

# ---------- SlurmDBD ----------
echo "=> 設定 SlurmDBD"
mkdir -p /etc/slurm /var/log/slurm /run/slurm
cat > /etc/slurm/slurmdbd.conf <<DBDCONF
AuthType=auth/munge
DbdAddr=localhost
DbdHost=localhost
SlurmUser=slurm
DebugLevel=info
LogFile=/var/log/slurm/slurmdbd.log
PidFile=/run/slurm/slurmdbd.pid
StorageType=accounting_storage/mysql
StorageHost=localhost
StoragePass=$DB_PASSWORD
StorageUser=slurm
StorageLoc=slurm_acct_db
DBDCONF
chown slurm:slurm /etc/slurm/slurmdbd.conf
chmod 600 /etc/slurm/slurmdbd.conf
chown slurm:slurm /var/log/slurm /run/slurm
systemctl enable --now slurmdbd

# ---------- slurm.conf ----------
echo "=> 設定 slurm.conf"
cat > /etc/slurm/slurm.conf <<SLURMCONF
ClusterName=$CLUSTER_NAME
SlurmctldHost=$CONTROLLER_HOSTNAME
MpiDefault=none
ProctrackType=proctrack/cgroup
ReturnToService=2
SlurmctldPidFile=/run/slurm/slurmctld.pid
SlurmctldPort=6817
SlurmdPidFile=/run/slurm/slurmd.pid
SlurmdPort=6818
SlurmdSpoolDir=/var/spool/slurmd
SlurmUser=slurm
StateSaveLocation=/var/spool/slurmctld
SwitchType=switch/none
TaskPlugin=task/affinity
InactiveLimit=0
KillWait=30
MinJobAge=300
SlurmctldTimeout=120
SlurmdTimeout=300
Waittime=0
SchedulerType=sched/backfill
SelectType=select/cons_tres
AccountingStorageType=accounting_storage/slurmdbd
AccountingStorageHost=$CONTROLLER_HOSTNAME
JobCompType=jobcomp/none
JobAcctGatherFrequency=30
JobAcctGatherType=jobacct_gather/linux
SlurmctldDebug=info
SlurmctldLogFile=/var/log/slurm/slurmctld.log
SlurmdDebug=info
SlurmdLogFile=/var/log/slurm/slurmd.log
# --- Node definitions (compute only — headnode is not a partition member) ---
%{ for name in compute_nodes ~}
NodeName=${name} CPUs=${node_cpus} State=UNKNOWN
%{ endfor ~}
# --- Partition definitions ---
PartitionName=all Nodes=${join(",", compute_nodes)} MaxTime=INFINITE State=UP
%{ if length(compute_nodes_odd) > 0 ~}
PartitionName=odd Nodes=${join(",", compute_nodes_odd)} Default=YES MaxTime=INFINITE State=UP
%{ endif ~}
%{ if length(compute_nodes_even) > 0 ~}
PartitionName=even Nodes=${join(",", compute_nodes_even)} MaxTime=INFINITE State=UP
%{ endif ~}
SLURMCONF

# ---------- Slurmctld ----------
echo "=> 啟動 Slurmctld"
mkdir -p /var/spool/slurmctld /var/spool/slurmd
chown slurm:slurm /var/spool/slurmctld /var/spool/slurmd
systemctl enable --now slurmctld

# Register cluster
sleep 5
sacctmgr -i add cluster "$CLUSTER_NAME" || true

# ---------- Share config via NFS ----------
echo "=> 將設定檔派發至共享目錄"
cp /etc/slurm/slurm.conf "$SLURM_CONF_SYNC"
chmod 644 "$SLURM_CONF_SYNC"

echo "========== Head Node 安裝完成 =========="
