#!/bin/bash
# Slurm Compute Node installation (NFS client + Munge + Slurmd)
# Generated by Terraform — do not edit manually.
set -e

NODE_HOSTNAME="${node_hostname}"
CONTROLLER_HOSTNAME="${controller_hostname}"
CONTROLLER_IP="${controller_ip}"
NFS_SHARE_DIR="${nfs_share_dir}"
MUNGE_KEY_SOURCE="$NFS_SHARE_DIR/munge.key.sync"
SLURM_CONF_SOURCE="$NFS_SHARE_DIR/slurm.conf.sync"

echo "========== 開始安裝 Compute Node ($NODE_HOSTNAME) =========="

# Set hostname
hostnamectl set-hostname "$NODE_HOSTNAME"

# Create dummy0 interface for neutron_external_interface
modprobe dummy
ip link add dummy0 type dummy
ip link set dummy0 up

# Persist dummy module and interface across reboots
echo "dummy" > /etc/modules-load.d/dummy.conf
nmcli connection add type dummy ifname dummy0 con-name dummy0 autoconnect yes

# Add headnode and self to /etc/hosts
NODE_IP=$(hostname -I | awk '{print $1}')
echo "$CONTROLLER_IP $CONTROLLER_HOSTNAME" >> /etc/hosts
echo "$NODE_IP $NODE_HOSTNAME" >> /etc/hosts

# ---------- packages ----------
echo "=> 安裝基礎套件"
dnf install -y epel-release
# Rocky 8 uses 'powertools'; Rocky 9 uses 'crb'
OS_VER=$(rpm -E '%%{rhel}')
if [ "$OS_VER" = "8" ]; then
    dnf config-manager --set-enabled powertools
else
    dnf config-manager --set-enabled crb
fi
dnf install -y munge munge-libs munge-devel slurm slurm-slurmd slurm-pam_slurm \
    nfs-utils apptainer checkpolicy policycoreutils-python-utils

# ---------- users ----------
echo "=> 確保 slurm / munge 使用者與群組存在"
getent group slurm  >/dev/null || groupadd -r slurm
getent passwd slurm >/dev/null || useradd -r -g slurm -s /bin/nologin -d /nonexistent slurm
getent group munge  >/dev/null || groupadd -r munge
getent passwd munge >/dev/null || useradd -r -g munge -s /bin/nologin -d /nonexistent munge

# 建立 test-user (固定 UID/GID 1100， home dir 來自 NFS 共享目錄，不建立本機目錄)
echo "=> 建立 test-user 帳號 (no-create-home)"
getent group test-user >/dev/null || groupadd -g 1100 test-user
id test-user &>/dev/null     || useradd -M -u 1100 -g 1100 -s /bin/bash test-user
echo "test-user:${test_user_password}" | chpasswd


# ---------- sudoers ----------
echo "=> 設定 sudoers 權限"
cat > /etc/sudoers.d/cloud-user <<SUDOERS
${sudoers_content}
SUDOERS
chmod 0440 /etc/sudoers.d/cloud-user

# ---------- NFS Client ----------
echo "=> 設定 NFS Client 並掛載 $NFS_SHARE_DIR"
if ! grep -q "$CONTROLLER_IP:$NFS_SHARE_DIR" /etc/fstab; then
    echo "$CONTROLLER_IP:$NFS_SHARE_DIR $NFS_SHARE_DIR nfs defaults 0 0" >> /etc/fstab
fi
# Retry mount — headnode NFS may still be starting
for i in $(seq 1 30); do
    mount -a && break
    echo "Waiting for NFS server... attempt $i"
    sleep 10
done

# ---------- MUNGE ----------
echo "=> 設定 MUNGE (Compute)"
if [ -f "$MUNGE_KEY_SOURCE" ]; then
    cp "$MUNGE_KEY_SOURCE" /etc/munge/munge.key
    chown munge:munge /etc/munge/munge.key
    chmod 400 /etc/munge/munge.key
else
    echo "錯誤：找不到 $MUNGE_KEY_SOURCE，等待 NFS 資源就緒..."
    for i in $(seq 1 30); do
        sleep 10
        if [ -f "$MUNGE_KEY_SOURCE" ]; then
            cp "$MUNGE_KEY_SOURCE" /etc/munge/munge.key
            chown munge:munge /etc/munge/munge.key
            chmod 400 /etc/munge/munge.key
            break
        fi
    done
fi
systemctl enable --now munge

# ---------- Slurmd ----------
echo "=> 設定 Slurmd"
if [ -f "$SLURM_CONF_SOURCE" ]; then
    mkdir -p /etc/slurm
    cp "$SLURM_CONF_SOURCE" /etc/slurm/slurm.conf
    chown slurm:slurm /etc/slurm/slurm.conf
else
    echo "等待 slurm.conf 出現在共享目錄..."
    for i in $(seq 1 30); do
        sleep 10
        if [ -f "$SLURM_CONF_SOURCE" ]; then
            mkdir -p /etc/slurm
            cp "$SLURM_CONF_SOURCE" /etc/slurm/slurm.conf
            chown slurm:slurm /etc/slurm/slurm.conf
            break
        fi
    done
fi
mkdir -p /var/spool/slurmd /var/log/slurm /run/slurm
chown slurm:slurm /var/spool/slurmd /var/log/slurm /run/slurm
systemctl enable --now slurmd

# ---------- pam_slurm_adopt: access.conf ----------
echo "=> 設定 /etc/security/access.conf"
if ! grep -q "pam_slurm_adopt managed" /etc/security/access.conf 2>/dev/null; then
    cat >> /etc/security/access.conf <<ACCESSCONF
# --- pam_slurm_adopt managed block ---
+:root:ALL
+:cloud-user:ALL
-:ALL:ALL
# --- end pam_slurm_adopt managed block ---
ACCESSCONF
fi

# ---------- pam_slurm_adopt: /etc/pam.d/sshd ----------
echo "=> 設定 /etc/pam.d/sshd"
if ! grep -q "pam_slurm_adopt.so" /etc/pam.d/sshd; then
    sed -i '/^account.*include.*password-auth/a account    sufficient   pam_access.so' /etc/pam.d/sshd
    sed -i '/^account    sufficient   pam_access.so/a -account   required     pam_slurm_adopt.so action_adopt_failure=deny action_generic_failure=deny' /etc/pam.d/sshd
fi

# ---------- pam_slurm_adopt: SELinux 設為 permissive ----------
echo "=> 將 SELinux 設為 permissive (立即生效 + 永久生效)"
setenforce 0 || true
if [ -f /etc/selinux/config ]; then
    sed -i 's/^SELINUX=enforcing/SELINUX=permissive/' /etc/selinux/config
    sed -i 's/^SELINUX=disabled/SELINUX=permissive/' /etc/selinux/config
fi

systemctl restart sshd

echo "========== Compute Node ($NODE_HOSTNAME) 安裝完成 =========="
