#!/bin/bash
# Slurm Compute Node installation (NFS client + Munge + Slurmd)
# Generated by Terraform — do not edit manually.
set -e

NODE_HOSTNAME="${node_hostname}"
CONTROLLER_HOSTNAME="${controller_hostname}"
CONTROLLER_IP="${controller_ip}"
NFS_SHARE_DIR="${nfs_share_dir}"
MUNGE_KEY_SOURCE="$NFS_SHARE_DIR/munge.key.sync"
SLURM_CONF_SOURCE="$NFS_SHARE_DIR/slurm.conf.sync"

echo "========== 開始安裝 Compute Node ($NODE_HOSTNAME) =========="

# Set hostname
hostnamectl set-hostname "$NODE_HOSTNAME"

# Add headnode and self to /etc/hosts
NODE_IP=$(hostname -I | awk '{print $1}')
echo "$CONTROLLER_IP $CONTROLLER_HOSTNAME" >> /etc/hosts
echo "$NODE_IP $NODE_HOSTNAME" >> /etc/hosts

# ---------- packages ----------
echo "=> 安裝基礎套件"
dnf install -y epel-release
dnf config-manager --set-enabled crb
dnf install -y munge munge-libs munge-devel slurm slurm-slurmd nfs-utils apptainer

# ---------- users ----------
echo "=> 確保 slurm / munge 使用者與群組存在"
getent group slurm  >/dev/null || groupadd -r slurm
getent passwd slurm >/dev/null || useradd -r -g slurm -s /bin/nologin -d /nonexistent slurm
getent group munge  >/dev/null || groupadd -r munge
getent passwd munge >/dev/null || useradd -r -g munge -s /bin/nologin -d /nonexistent munge

# ---------- NFS Client ----------
echo "=> 設定 NFS Client 並掛載 $NFS_SHARE_DIR"
if ! grep -q "$CONTROLLER_IP:$NFS_SHARE_DIR" /etc/fstab; then
    echo "$CONTROLLER_IP:$NFS_SHARE_DIR $NFS_SHARE_DIR nfs defaults 0 0" >> /etc/fstab
fi
# Retry mount — headnode NFS may still be starting
for i in $(seq 1 30); do
    mount -a && break
    echo "Waiting for NFS server... attempt $i"
    sleep 10
done

# ---------- MUNGE ----------
echo "=> 設定 MUNGE (Compute)"
if [ -f "$MUNGE_KEY_SOURCE" ]; then
    cp "$MUNGE_KEY_SOURCE" /etc/munge/munge.key
    chown munge:munge /etc/munge/munge.key
    chmod 400 /etc/munge/munge.key
else
    echo "錯誤：找不到 $MUNGE_KEY_SOURCE，等待 NFS 資源就緒..."
    for i in $(seq 1 30); do
        sleep 10
        if [ -f "$MUNGE_KEY_SOURCE" ]; then
            cp "$MUNGE_KEY_SOURCE" /etc/munge/munge.key
            chown munge:munge /etc/munge/munge.key
            chmod 400 /etc/munge/munge.key
            break
        fi
    done
fi
systemctl enable --now munge

# ---------- Slurmd ----------
echo "=> 設定 Slurmd"
if [ -f "$SLURM_CONF_SOURCE" ]; then
    mkdir -p /etc/slurm
    cp "$SLURM_CONF_SOURCE" /etc/slurm/slurm.conf
    chown slurm:slurm /etc/slurm/slurm.conf
else
    echo "等待 slurm.conf 出現在共享目錄..."
    for i in $(seq 1 30); do
        sleep 10
        if [ -f "$SLURM_CONF_SOURCE" ]; then
            mkdir -p /etc/slurm
            cp "$SLURM_CONF_SOURCE" /etc/slurm/slurm.conf
            chown slurm:slurm /etc/slurm/slurm.conf
            break
        fi
    done
fi
mkdir -p /var/spool/slurmd /var/log/slurm /run/slurm
chown slurm:slurm /var/spool/slurmd /var/log/slurm /run/slurm
systemctl enable --now slurmd

echo "========== Compute Node ($NODE_HOSTNAME) 安裝完成 =========="
