# Sudoers for cloud-user to manage OpenStack nodes on Slurm
# Generated by Terraform - do not edit manually.

# 基礎維運指令 (需密碼)
cloud-user ALL=(ALL) /usr/bin/systemctl, /usr/bin/dnf, /usr/sbin/reboot, /usr/sbin/usermod, /usr/sbin/groupadd, /usr/bin/ls, /usr/bin/md5sum, /usr/bin/sinfo

# 限制 mkdir 僅能建立必要的目錄結構 (需密碼)
cloud-user ALL=(ALL) /usr/bin/mkdir -p /etc/docker, /usr/bin/mkdir -p /kolla_nfs, /usr/bin/mkdir -p /etc/slurm, /usr/bin/mkdir -p /var/spool/slurmd, /usr/bin/mkdir -p /var/log/slurm, /usr/bin/mkdir -p /run/slurm, /usr/bin/mkdir -p /var/spool/slurmctld

# 限制 tee 僅能寫入特定的系統設定檔 (需密碼)
cloud-user ALL=(ALL) /usr/bin/tee /etc/docker/daemon.json, /usr/bin/tee -a /etc/hosts
